const COMMON_PM2 = {
  env: { NODE_ENV: 'production' },
  restart_delay: 5000,
  min_uptime: '10s',
  max_restarts: 10,
  log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  merge_logs: true,
  watch: false,
};

module.exports = {
  apps: [
    {
      name: 'web',
      cwd: './apps/web',
      script: 'node_modules/.bin/next',
      args: 'start',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3000 },
      max_memory_restart: '512M',
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
    },
    {
      name: 'workflow-engine',
      cwd: './services/workflow-engine',
      script: 'dist/index.js',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3011 },
      max_memory_restart: '256M',
      error_file: './logs/workflow-engine-error.log',
      out_file: './logs/workflow-engine-out.log',
    },
    {
      name: 'production-pipeline',
      cwd: './services/production-pipeline',
      script: 'dist/index.js',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3002 },
      max_memory_restart: '256M',
      error_file: './logs/production-pipeline-error.log',
      out_file: './logs/production-pipeline-out.log',
    },
    {
      name: 'ai-assistant',
      cwd: './services/ai-assistant',
      script: 'dist/index.js',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3003 },
      max_memory_restart: '256M',
      error_file: './logs/ai-assistant-error.log',
      out_file: './logs/ai-assistant-out.log',
    },
    {
      name: 'worker-content',
      cwd: '.',
      script: 'workers/dist/content.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '256M',
      error_file: './logs/worker-content-error.log',
      out_file: './logs/worker-content-out.log',
    },
    {
      name: 'worker-account',
      cwd: '.',
      script: 'workers/dist/account.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '512M',
      error_file: './logs/worker-account-error.log',
      out_file: './logs/worker-account-out.log',
    },
    {
      name: 'worker-posting',
      cwd: '.',
      script: 'workers/dist/posting.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '256M',
      error_file: './logs/worker-posting-error.log',
      out_file: './logs/worker-posting-out.log',
    },
    {
      name: 'worker-research',
      cwd: '.',
      script: 'workers/dist/research.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '256M',
      error_file: './logs/worker-research-error.log',
      out_file: './logs/worker-research-out.log',
    },
    {
      name: 'worker-maintenance',
      cwd: '.',
      script: 'workers/dist/maintenance.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '128M',
      error_file: './logs/worker-maintenance-error.log',
      out_file: './logs/worker-maintenance-out.log',
    },
    {
      name: 'worker-production',
      cwd: '.',
      script: 'workers/dist/production.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '512M',
      error_file: './logs/worker-production-error.log',
      out_file: './logs/worker-production-out.log',
    },
    {
      name: 'worker-experiment',
      cwd: '.',
      script: 'workers/dist/experiment.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '256M',
      error_file: './logs/worker-experiment-error.log',
      out_file: './logs/worker-experiment-out.log',
    },
    {
      name: 'worker-lifecycle',
      cwd: '.',
      script: 'workers/dist/lifecycle.worker.js',
      ...COMMON_PM2,
      max_memory_restart: '256M',
      error_file: './logs/worker-lifecycle-error.log',
      out_file: './logs/worker-lifecycle-out.log',
    },
  ],
};
