const COMMON_PM2 = {
  env: { NODE_ENV: 'production' },
  restart_delay: 5000,
  min_uptime: '10s',
  max_restarts: 10,
  log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  merge_logs: true,
  watch: false,
};

module.exports = {
  apps: [
    {
      name: 'web',
      cwd: './apps/web',
      script: 'node_modules/.bin/next',
      args: 'start',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3000 },
      max_memory_restart: '512M',
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
    },
    {
      name: 'workflow-engine',
      cwd: './services/workflow-engine',
      script: 'dist/index.js',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3011 },
      max_memory_restart: '256M',
      error_file: './logs/workflow-engine-error.log',
      out_file: './logs/workflow-engine-out.log',
    },
    {
      name: 'production-pipeline',
      cwd: './services/production-pipeline',
      script: 'dist/index.js',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3002 },
      max_memory_restart: '256M',
      error_file: './logs/production-pipeline-error.log',
      out_file: './logs/production-pipeline-out.log',
    },
    {
      name: 'ai-assistant',
      cwd: './services/ai-assistant',
      script: 'dist/index.js',
      ...COMMON_PM2,
      env: { ...COMMON_PM2.env, PORT: 3003 },
      max_memory_restart: '256M',
      error_file: './logs/ai-assistant-error.log',
      out_file: './logs/ai-assistant-out.log',
    },
    {
      name: 'workers',
      cwd: '.',
      script: 'workers/dist/index.js',
      ...COMMON_PM2,
      max_memory_restart: '512M',
      error_file: './logs/workers-error.log',
      out_file: './logs/workers-out.log',
    },
  ],
};
